data:
 num_workers: 4
 pin_memory: False

model:
  name: 'resnet20_DAQ'
  params:
    pretrained: False
    num_classes: 10
    num_bit: 1
    a_sig: 2
    a_temp: 2
  pretrain: 
    pretrained: True
    dir: './results/cifar10_fp.pth'

train:
  dir: './results'
  batch_size: 256
  num_epochs: 400
  model_dir: '.W1A1'

eval:
  batch_size: 100

scheduler:
  name: 'cosine'
  params:
    T_max: 400
    eta_min: 0

optimizer:
  name: sgd
  params:
    lr: 0.1
    weight_decay: 0.0001

q_optimizer:
  name: adam
  params:
    lr: 0.0001
    weight_decay: 0.0

loss:
  name: 'cross_entropy'
  params:
    reduction: 'mean'

gpu: 0
